services:
  app:
    build:
      context: ./app
    ports:
      - "9000:9000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/movies
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movies
    ports:
      - "5432:5432"

volumes:
  db_data:
